name: Publish to PyPI

on:
    push:
      tags:        
        - '*'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment: release
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install hatch
    - name: Get the editor
      run: bash update_editor.sh
    - name: Build package
      run: hatch build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1